# Generated by Django 3.1 on 2020-08-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
