# Generated by Django 3.1 on 2020-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='env_point',
            field=models.IntegerField(null=True),
        ),
    ]
