# Generated by Django 3.1 on 2020-09-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_business_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_number',
        ),
    ]
