# Generated by Django 3.1 on 2020-10-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_env_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='env_point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
