# Generated by Django 3.1 on 2020-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_user_business_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_address',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
