# Generated by Django 3.1 on 2020-10-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20201013_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='env_point',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
