# Generated by Django 3.1 on 2020-10-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20201013_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='env_point',
        ),
        migrations.AddField(
            model_name='user',
            name='env_money',
            field=models.IntegerField(null=True),
        ),
    ]
