# Generated by Django 3.1 on 2020-10-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='env_money',
        ),
    ]
