# Generated by Django 3.1 on 2020-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_remove_user_env_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='env_money',
            field=models.IntegerField(null=True),
        ),
    ]
