# Generated by Django 3.1 on 2020-09-16 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200916_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='available_display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='available_order',
            field=models.BooleanField(default=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='restaurant',
            index_together={('id', 'slug')},
        ),
    ]
