# Generated by Django 3.1 on 2020-09-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200917_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('buylist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buylists', to='shop.category')),
            ],
        ),
    ]
