# Generated by Django 3.1 on 2020-10-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201003_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Register', to='shop.product'),
        ),
    ]
