# Generated by Django 3.1.2 on 2020-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
