# Generated by Django 3.1 on 2020-10-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_number',
            field=models.CharField(default=1, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='callnumber',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opentime',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
