# Generated by Django 3.1.2 on 2020-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_restaurant_business_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='call_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
