# Generated by Django 3.1 on 2020-10-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201020_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='callnumber',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opentime',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='call_number',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
