# Generated by Django 3.1 on 2020-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201020_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
