# Generated by Django 3.1 on 2020-10-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201020_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='business_number',
            new_name='business_number2',
        ),
    ]
