# Generated by Django 3.1 on 2020-10-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commnet',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='shop.restaurant'),
        ),
    ]
