# Generated by Django 3.1 on 2020-10-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201020_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='business_number2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='call_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='open_time',
        ),
    ]
